### ISSUE TITLE
TODO: Revert back `terraform-docs` repo

### ISSUE THREAD

**Issue by michaelsaki** [cisagov/skeleton-generic#165]
# 💡 Summary #

We need to revert back to using the main `terraform-docs` repo after https://github.com/terraform-docs/terraform-docs/pull/745 has been merged. 

## Motivation and context ##

We are currently using a forked branch @mcdonnnj made to allow ATX header support for `terraform-docs`. Once his branch has been approved we should revert back to the standard of pulling from the main repo of `terraform-docs`.

## Implementation notes ##

Implementation would be as follows:

- edit the `build.yml` workflow to pull from the main repo of `terraform-docs`
- this is a `TODO` from https://github.com/cisagov/skeleton-generic/pull/164

## Acceptance criteria ##

- [ ] https://github.com/terraform-docs/terraform-docs/pull/745 has been merged into the main repo of `terraform-docs`
- [ ] the workflow has been reverted back to use the main repo of `terraform-docs`
- [ ] clean up any unnecessary variables or comments that were made during https://github.com/cisagov/skeleton-generic/pull/164
